name: app_location
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_maps: ^20.4.54
  flutter_rating_bar: ^4.0.0
  latlong2: 0.9.1
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
